# Generated by Django 2.2.5 on 2019-09-29 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 17, 50, 48, 559588), verbose_name='date published'),
        ),
    ]
