# Generated by Django 2.2.5 on 2019-10-13 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190929_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=200)),
                ('content_content', models.TextField()),
                ('content_published', models.DateTimeField(default=datetime.datetime(2019, 10, 13, 18, 12, 3, 785009), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
