# Generated by Django 2.1 on 2019-12-07 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=200)),
                ('content_content', models.TextField()),
                ('content_published', models.DateTimeField(default=datetime.datetime(2019, 12, 7, 11, 39, 42, 644256), verbose_name='date published')),
            ],
        ),
    ]
