# Generated by Django 2.2 on 2019-11-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191110_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 14, 9, 2, 240958), verbose_name='date published'),
        ),
    ]
